package view

var configFileIcons = map[string]string{
	".env":                "config",
	".env.example":        "config",
	".env.local":          "config",
	".eslintrc":           "config",
	".gitignore":          "git",
	".npmrc":              "config",
	".prettierrc":         "config",
	".serverigh":          "config",
	"codeowners":          "text",
	"deno.json":           "json",
	"deno.lock":           "lock",
	"docker-compose.yml":  "docker",
	"docker-compose.yaml": "docker",
	"dockerfile":          "docker",
	"editorconfig":        "config",
	"eslint.config.js":    "javascript",
	"eslint.config.mjs":   "javascript",
	"eslint.config.ts":    "typescript",
	"package-lock.json":   "lock",
	"pnpm-lock.yaml":      "lock",
	"tsconfig.json":       "typescript",
	"yarn.lock":           "lock",
}

var configCompoundIcons = map[string]string{
	".config.cjs":  "javascript",
	".config.js":   "javascript",
	".config.mjs":  "javascript",
	".config.ts":   "typescript",
	".d.ts":        "typescript",
	".env":         "config",
	".lock":        "lock",
	".module.css":  "css",
	".module.scss": "css",
	".toml":        "config",
	".yaml":        "config",
	".yml":         "config",
}

var configExtensionIcons = map[string]string{
	".cfg":          "config",
	".conf":         "config",
	".config":       "config",
	".editorconfig": "config",
	".env":          "config",
	".hcl":          "config",
	".ini":          "config",
	".jsonc":        "json",
	".lock":         "lock",
	".properties":   "config",
	".service":      "config",
	".tf":           "config",
	".tfvars":       "config",
	".toml":         "config",
	".yaml":         "config",
	".yml":          "config",
}
